fob=open("f2.txt","w")
print("ok")
fob.write("hii how are you")
fob.close()
fob1=open("f1.txt","w")
print("okk")
fob1.write("chanti")
fob1.close()
fob=open("f2.txt","r")
text=fob.read()
fob.close()
fob1=open("f1.txt","r")
text1=fob1.read()
fob1.close()
print("okkk")
fob2=open("f3.txt","w")
fob2.write(text+text1)
fob2.close()
print("okkkk")

